image:
  repository: myregistry/order-service
  tag: latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: order-service.dev.example.com
  path: /
  annotations:
    kubernetes.io/ingress.class: alb

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

replicaCount: 2

environment:
  NODE_ENV: development
  DATABASE_URL: postgres://user:password@db:5432/order_service_dev