apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YadinDeri/gitops-test.git # 👈 your GitHub repo
    targetRevision: main
    path: nginxapp # 👈 I will explain about this path in a second
  destination:
    server: https://kubernetes.default.svc
    namespace: nginxapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true